
#' @name setUpCch
#' @title Set-up a cache
#' @description Creates a cache of parameters in the wd.
#' @param wd Working directory
#' @param prmtrs Paramters list generated by \code{setUpPrmtrs}.
#' @param ovrwrt Overwrite existing cache? Default FALSE.
#' @details Warning: overwriting with this function will
#' delete the existing cache.
#' @export
setUpCch <- function(wd, prmtrs, ovrwrt=FALSE) {
  d <- file.path(wd, 'cache')
  if(file.exists(d)) {
    if(!ovrwrt) {
      stop('Cache already exists, ovrwrt=FALSE.')
    } else {
      rmCch(wd)
    }
  }
  dir.create(d)
  saveRDS(object=prmtrs,
          file=file.path(d, 'prmtrs.RData'))
}

#' @name ldPrmtrs
#' @title Load paramters from cache
#' @description Parameters are held in cache, use
#' this function to load parameters set for a wd.
#' @param wd Working directory
#' @export
ldPrmtrs <- function(wd) {
  fl <- file.path(wd, 'cache', 'prmtrs.RData')
  if(file.exists(fl)) {
    prmtrs <- readRDS(file=fl)
  } else {
    stop('Cache does not exist.')
  }
  prmtrs
}

#' @name chkObj
#' @title Check if an object exists
#' @description Check if an object exists in the cache.
#' @param wd Working directory
#' @param nm Object name
#' @export
chkObj <- function(wd, nm) {
  fl <- file.path(wd, 'cache', paste0(nm, '.RData'))
  file.exists(fl)
}

#' @name ldObj
#' @title Load a named object from the cache
#' @description Loads an object from the cache
#' as stored by \code{svObj}
#' @param wd Working directory
#' @param nm Object name
#' @export
ldObj <- function(wd, nm) {
  fl <- file.path(wd, 'cache', paste0(nm, '.RData'))
  if(!file.exists(fl)) {
    stop(paste0('No [', nm, '] in [',
                wd, '] cache.'))
  }
  readRDS(file=fl)
}

#' @name svObj
#' @title Aave a named object in the cache
#' @description Save an object in the cache
#' that can be loaded by \code{ldObj}
#' @param wd Working directory
#' @param obj Object
#' @param nm Object name
#' @export
svObj <- function(wd, obj, nm) {
  d <- file.path(wd, 'cache')
  if(!file.exists(d)) {
    dir.create(d)
  }
  fl <- file.path(wd, 'cache', paste0(nm, '.RData'))
  saveRDS(object=obj, file=fl)
}

#' @name rmCch
#' @title Delete a cache
#' @description Deletes a cache from a wd.
#' @param wd Working directory
#' @export
rmCch <- function(wd) {
  d <- file.path(wd, 'cache')
  if(file.exists(d)) {
    unlink(d, recursive=TRUE)
  }
}

#' @name svSqs
#' @title Save sequences to cache
#' @description Saves sequences downloaded \code{getSqs}
#' and converted to data.frame.
#' @param wd Working directory
#' @param txid Taxonomic ID, numeric
#' @param sqdf Sequence data.frame
#' @details Used within the \code{dwnld} function. Saves
#' sequence data by txid in cache.
#' @export
svSqs <- function(wd=wd, txid=txid, sqdf=sqdf) {
  # TODO: avoid overwriting
  d <- file.path(wd, 'cache')
  if(!file.exists(d)) {
    stop('Cache does not exist.')
  }
  d <- file.path(d, 'sqs')
  if(!file.exists(d)) {
    dir.create(d)
  }
  fl <- file.path(d, paste0(txid, '.RData'))
  saveRDS(object=sqdf, file=fl)
}

#' @name ldSqs
#' @title Load sequences from cache
#' @description Load sequences downloaded by
#' \code{dwnld} function.
#' @param wd Working directory
#' @param txid Taxonomic ID, numeric
#' @export
ldSqs <- function(wd=wd, txid=txid, sqdf=sqdf) {
  d <- file.path(wd, 'cache')
  if(!file.exists(d)) {
    stop('Cache does not exist.')
  }
  d <- file.path(d, 'sqs')
  if(!file.exists(d)) {
    stop('`sqs` not in cache. Have you run the download stage?')
  }
  fl <- file.path(d, paste0(txid, '.RData'))
  if(!file.exists(fl)) {
    stop(paste0('[', txid, '] not in `sqs` of cache.'))
  }
  readRDS(file=fl)
}