# Control cache-ing of data through the same functions

#' @name setUpCch
#' @title Set-up a cache
#' @description Creates a cache of parameters in the wd.
#' @param wd Working directory
#' @param prmtrs Paramters list generated by \code{setUpPrmtrs}.
#' @param ovrwrt Overwrite existing cache? Default FALSE.
#' @details Warning: overwriting with this function will
#' delete the existing cache.
#' @export
setUpCch <- function(wd, prmtrs, ovrwrt=FALSE) {
  d <- file.path(wd, 'cache')
  if(file.exists(d)) {
    if(!ovrwrt) {
      stop('Cache already exists, ovrwrt=FALSE.')
    } else {
      rmCch(wd)
    }
  }
  dir.create(d)
  saveRDS(object=prmtrs,
          file=file.path(d, 'prmtrs.RData'))
}

#' @name ldPrmtrs
#' @title Load paramters from cache
#' @description Parameters are held in cache, use
#' this function to load parameters set for a wd.
#' @param wd Working directory
#' @export
ldPrmtrs <- function(wd) {
  fl <- file.path(wd, 'cache', 'prmtrs.RData')
  if(file.exists(fl)) {
    prmtrs <- readRDS(file=fl)
  } else {
    stop('Cache does not exist.')
  }
  prmtrs
}

#' @name rmCch
#' @title Delete a cache
#' @description Deletes a cache from a wd.
#' @param wd Working directory
#' @export
rmCch <- function(wd) {
  d <- file.path(wd, 'cache')
  if(file.exists(d)) {
    unlink(d, recursive=TRUE)
  }
}