

#' @name setUpPrmtrs
#' @title Return run parameters
#' @description Provide parameters for a pipeline run
#' @param wd Working directory
#' @param txid Root taxonomic ID(s), vector or numeric
#' @param ncbi_execs File directories for NCBI tools, see \code{setUpNcbiTools()}
#' @param tdpth NCBI taxdump.tar.gz
#' @param mx_dscndnts Maximum number of descendants per taxonomic node, numeric
#' @param tmout Timeout in seconds, numeric.
#' @param mdl_thrshld Maximum number of sequences per species
#' @param mx_blst_sqs Maximum number of sequences to blast in a single run;
#' @param mx_sq_lngth Maximum characters in one sequence
#' @param sq_cch_dr Directory for sequence cache; will be created if does not exist
#' @param cores Number of cores for parellisation 
#' @details
#' ncbi_execs: users must run \code{setUpNcbiTools()} before running pipeline
#' mx_blst_sqs: if taxon has more subtree sequences than that,
#' its children will get clustered.
#' cores: set to 1 to run sequentially
#' @export
#' @seealso
#' \link{setUpNcbiTools}
setUpPrmtrs <- function(wd, txid, ncbi_execs,
                        tdpth=NULL,
                        mx_dscndnts=10000,
                        tmout=100,
                        mdl_thrshld=3000,
                        mx_blst_sqs=10000,
                        mx_sq_lngth=25000,
                        sq_cch_dr="sequences",
                        verbose=FALSE,
                        cores=1) {
  if(!file.exists(wd)) {
    stop('Invalid `wd`. [', wd, '] does not exit.\n')
  }
  prmtrs <- list(txid=txid, tdpth=tdpth,
                 mx_dscndnts=mx_dscndnts,
                 tmout=tmout,
                 mdl_thrshld=mdl_thrshld,
                 mx_blst_sqs=mx_blst_sqs,
                 mx_sq_lngth=mx_sq_lngth,
                 sq_cch_dr=sq_cch_dr,
                 verbose=verbose,
                 cores=cores)
  if(sum(names(ncbi_execs) %in%
         c('mkblstdb', 'blstn')) == 2) {
    prmtrs <- c(prmtrs, ncbi_execs)
  } else {
    stop('Invalid NCBI execs provided.
         Must be named list as generated by `setUpNcbiTools`')
  }
  if(cores > 1) {
    os <- .Platform$OS.type
    if(grepl('windows', os)) {
      doSNOW::registerDoMC(cores)
    } else if (grepl('unix', os)) {
      doMC::registerDoMC(cores)
    } else {
      warning('Unknown OS. Unable to use `foreach` parallelisation.')
    }
  }
  setUpCch(wd=wd, prmtrs=prmtrs)
}

#' @name setUpNcbiTools
#' @title Ensures NCBI BLAST tools are installed
#' @description Ensures NCBI BLAST executables are installed on the 
#' system. Tests version number of BLAST tools.
#' @param d Directory to NCBI BLAST tools
#' @details BLAST tools must be version >2.7.1.
#' @export
#' @seealso
#' \link{setUpPrmtrs}
setUpNcbiTools <- function(d) {
  sccdd <- TRUE
  mkblstdb <- file.path(d, 'makeblastdb')
  blstn <- file.path(d, 'blastn')
  for(ech in c(mkblstdb, blstn)) {
    cmd <- paste0(ech, ' -version')
    res <- try(system(cmd, intern = TRUE, ignore.stderr=TRUE),
               silent=TRUE)
    if(grepl('error', res[[1]], ignore.case=TRUE)) {
      tst <- FALSE
      cat('Invalid path: [', ech, '] \n', sep='')
      sccdd <- FALSE
    } else {
      # test version
      vrsn <- gsub('[a-zA-Z:+]', '', res[1])
      vrsn <- gsub('\\s', '', vrsn)
      vrsn <- as.numeric(strsplit(vrsn, '\\.')[[1]])
      tst <- vrsn[1] >= 2 & vrsn[2] >= 7 & vrsn[3] >= 1
      if(tst) {
        cat('Found: [', res[1], '] \n', sep='')
      } else {
        cat('Incorrect version: [', res[1], '] \n', sep='')
        sccdd <- FALSE
      }
    }
  }
  if(!sccdd) {
    stop('Unable to find correct versions of NCBI BLAST tools\n')
  }
  ncbi_execs <- list('mkblstdb'=mkblstdb,
                     'blstn'=blstn)
}