
#' @name setUpPrmtrs
#' @title Set Up Parameters
#' @description Initiates cache of parameters.
#' @param wd Working directory
#' @param ncbi_execs File directories for NCBI tools, see \code{setUpNcbiTools()}
#' @param ... Set parameters, see parameters()
#' @export
#' @seealso
#' \link{parameters}, \link{setUpNcbiTools}
setUpPrmtrs <- function(wd, ncbi_execs, ...) {
  if(!file.exists(wd)) {
    stop(paste0('Invalid `wd`. [', wd, '] does not exist.'))
  }
  # get parameters
  ps <- parameters(...)
  ps[['wd']] <- wd
  # calc wait times
  dff <- ps[['mxrtry']] - length(ps[['wt_tms']])
  if(dff > 0) {
    ps[['wt_tms']] <- c(ps[['wt_tms']],
                        rep(ps[['wt_tms']][length(ps[['wt_tms']])], dff))
  } else {
    ps[['wt_tms']] <- ps[['wt_tms']][1:ps[['mxrtry']]]
  }
  if(sum(names(ncbi_execs) %in%
         c('mkblstdb', 'blstn')) == 2) {
    ps[['mkblstdb']] <- ncbi_execs[['mkblstdb']]
    ps[['blstn']] <- ncbi_execs[['blstn']]
  } else {
    error(ps=ps, 'Invalid NCBI execs provided.
          Must be named list as generated by `setUpNcbiTools`')
  }
  if(ps[['ncps']] > 1) {
    os <- .Platform$OS.type
    if(grepl('windows', os)) {
      doSNOW::registerDoMC(ps[['ncps']])
    } else if (grepl('unix', os)) {
      doMC::registerDoMC(ps[['ncps']])
    } else {
      warn(ps=ps, 'Unknown OS.
           Unable to use `foreach` parallelisation.')
    }
  }
  # log parameters
  msg <- paste0('Setting up pipeline with the following parameters:')
  info(lvl=1, ps=ps, msg)
  mxnchrs <- max(sapply(names(ps), nchar)) + 3
  pnms <- names(ps)[names(ps) != 'wt_tms'] # too big to print
  pnms <- sort(pnms)
  for(pnm in pnms) {
    spcr <- paste0(rep(' ', mxnchrs - nchar(pnm)), collapse='')
    prmtr_msg <- paste0(pnm, spcr, '[', ps[[pnm]], ']')
    info(lvl=2, ps=ps, prmtr_msg)
  }
  setUpCch(ps=ps)
  intPrgrss(wd=wd)
}

#' @name setUpNcbiTools
#' @title Ensures NCBI BLAST tools are installed
#' @description Ensures NCBI BLAST executables are installed on the 
#' system. Tests version number of BLAST tools.
#' @param d Directory to NCBI BLAST tools
#' @param wd Working directory
#' @param v v, T/F
#' @details BLAST tools must be version >=2.0
#' @export
#' @seealso
#' \link{setUpPrmtrs}
setUpNcbiTools <- function(d, v, wd) {
  .log(v=v, wd=wd, 'Checking for valid NCBI BLAST+ Tools ...\n')
  sccdd <- TRUE
  mkblstdb <- file.path(d, 'makeblastdb')
  blstn <- file.path(d, 'blastn')
  for(ech in c(mkblstdb, blstn)) {
    args <- '-version'
    res <- try(.system(command=ech, args=args, stdout=TRUE,
                       stderr=FALSE), silent=TRUE)
    if(grepl('error', res[[1]], ignore.case=TRUE)) {
      tst <- FALSE
      .log(v=v, wd=wd, paste0('Invalid path: [', ech, ']\n'))
      sccdd <- FALSE
    } else {
      # test version
      vrsn <- gsub('[a-zA-Z:+]', '', res[1])
      vrsn <- gsub('\\s', '', vrsn)
      vrsn <- as.numeric(strsplit(vrsn, '\\.')[[1]])
      tst <- vrsn[1] >= 2 & vrsn[2] >= 0
      if(tst) {
        .log(v=v, wd=wd, paste0('Found: [', res[1], ']\n'))
      } else {
        .log(v=v, wd=wd, paste0('Incorrect version: [', res[1], ']\n'))
        sccdd <- FALSE
      }
    }
  }
  if(!sccdd) {
    msg <- 'Unable to find correct versions of NCBI BLAST+ tools\n'
    .log(v=v, wd=wd, paste0('Error:', msg))
    stop(msg)
  }
  ncbi_execs <- list('mkblstdb'=mkblstdb,
                     'blstn'=blstn)
}
