
#' @name setUpPrmtrs
#' @title Return run parameters
#' @description Provide parameters for a pipeline run
#' @param wd Working directory
#' @param txid Root taxonomic ID(s), vector or numeric
#' @param ncbi_execs File directories for NCBI tools, see \code{setUpNcbiTools()}
#' @param tdpth NCBI taxdump.tar.gz
#' @param mx_dscndnts Maximum number of descendants per taxonomic node, numeric
#' @param tmout Timeout in seconds, numeric.
#' @param mdl_thrshld Maximum number of sequences per species
#' @param mx_blst_sqs Maximum number of sequences to blast in a single run;
#' @param mx_sq_lngth Maximum characters in one sequence
#' @param sq_cch_dr Directory for sequence cache; will be created if does not exist
#' @param cores Number of cores for parellisation 
#' @details
#' ncbi_execs: users must run \code{setUpNcbiTools()} before running pipeline
#' mx_blst_sqs: if taxon has more subtree sequences than that,
#' its children will get clustered.
#' cores: set to 1 to run sequentially
#' @export
#' @seealso
#' \link{setUpNcbiTools}
setUpPrmtrs <- function(wd, txid, ncbi_execs,
                        tdpth=NULL, mxd=10000,
                        tmout=100, mdlt=3000,
                        mxsqs=1000, mxsql=25000,
                        mxretry=100, mxeval=1.0e-10,
                        mncvrg=0.51, v=FALSE, ncps=1) {
  if(!file.exists(wd)) {
    stop(paste0('Invalid `wd`. [', wd, '] does not exist.'))
  }
  # calc wait times
  wt_tms <- c(1, 3, 6, 10, 60, 300)
  dff <- mxretry - length(wt_tms)
  if(dff > 0) {
    wt_tms <- c(wt_tms, rep(wt_tms[length(wt_tms)], dff))
  } else {
    wt_tms <- wt_tms[1:mxretry]
  }
  ps <- list(txid=txid, tdpth=tdpth, mxd=mxd,
             tmout=tmout, mdlt=mdlt, mxsqs=mxsqs,
             mxsql=mxsql, v=v, ncps=ncps, wd=wd,
             mxretry=mxretry, mxeval=mxeval, wt_tms=wt_tms,
             mncvrg=mncvrg, lgfl=file.path(wd, 'log.txt'))
  if(sum(names(ncbi_execs) %in%
         c('mkblstdb', 'blstn')) == 2) {
    ps <- c(ps, ncbi_execs)
  } else {
    error(ps=ps, 'Invalid NCBI execs provided.
          Must be named list as generated by `setUpNcbiTools`')
  }
  if(ncps > 1) {
    os <- .Platform$OS.type
    if(grepl('windows', os)) {
      doSNOW::registerDoMC(ncps)
    } else if (grepl('unix', os)) {
      doMC::registerDoMC(ncps)
    } else {
      warn(ps=ps, 'Unknown OS.
           Unable to use `foreach` parallelisation.')
    }
  }
  # log parameters
  msg <- paste0('Setting up pipeline in with the following parameters:')
  info(lvl=1, ps=ps, msg)
  mxnchrs <- max(sapply(names(ps), nchar)) + 3
  for(prmtr in names(ps)) {
    spcr <- paste0(rep(' ', mxnchrs - nchar(prmtr)), collapse='')
    prmtr_msg <- paste0(prmtr, spcr, '[', ps[[prmtr]], ']')
    info(lvl=2, ps=ps, prmtr_msg)
  }
  setUpCch(ps=ps)
  intPrgrss(wd=wd)
}

#' @name setUpNcbiTools
#' @title Ensures NCBI BLAST tools are installed
#' @description Ensures NCBI BLAST executables are installed on the 
#' system. Tests version number of BLAST tools.
#' @param d Directory to NCBI BLAST tools
#' @param wd Working directory
#' @param v v, T/F
#' @details BLAST tools must be version >2.7.1.
#' @export
#' @seealso
#' \link{setUpPrmtrs}
setUpNcbiTools <- function(d, v, wd) {
  .log(v=v, wd=wd, 'Checking for valid NCBI BLAST+ Tools ...\n')
  sccdd <- TRUE
  mkblstdb <- file.path(d, 'makeblastdb')
  blstn <- file.path(d, 'blastn')
  for(ech in c(mkblstdb, blstn)) {
    args <- '-version'
    res <- try(.system(command=ech, args=args, stdout=TRUE,
                       stderr=FALSE), silent=TRUE)
    if(grepl('error', res[[1]], ignore.case=TRUE)) {
      tst <- FALSE
      .log(v=v, wd=wd, paste0('Invalid path: [', ech, ']\n'))
      sccdd <- FALSE
    } else {
      # test version
      vrsn <- gsub('[a-zA-Z:+]', '', res[1])
      vrsn <- gsub('\\s', '', vrsn)
      vrsn <- as.numeric(strsplit(vrsn, '\\.')[[1]])
      tst <- vrsn[1] >= 2 & vrsn[2] >= 7 & vrsn[3] >= 1
      if(tst) {
        .log(v=v, wd=wd, paste0('Found: [', res[1], ']\n'))
      } else {
        .log(v=v, wd=wd, paste0('Incorrect version: [', res[1], ']\n'))
        sccdd <- FALSE
      }
    }
  }
  if(!sccdd) {
    msg <- 'Unable to find correct versions of NCBI BLAST+ tools\n'
    .log(v=v, wd=wd, paste0('Error:', msg))
    stop(msg)
  }
  ncbi_execs <- list('mkblstdb'=mkblstdb,
                     'blstn'=blstn)
}