
#' @name intPrgrss
#' @title Initialise progress list in cache
#' @description Creates a progress list recording each
#' stage run in cache
#' @param wd Working directory
intPrgrss <- function(wd) {
  prgrss <- rep(FALSE, 4)
  names(prgrss) <- c('taxise', 'download',
                     'cluster', 'align')
  fl <- file.path(wd, 'cache', 'progress.RData')
  saveRDS(object=prgrss, file=fl)
}

#' @name svPrgrss
#' @title Save current progress
#' @description Stores the pipeline progress in the cache.
#' @param wd Working directory
#' @param stg Stage
svPrgrss <- function(wd, stg) {
  fl <- file.path(wd, 'cache', 'progress.RData')
  prgrss <- readRDS(file=fl)
  prgrss[[stg]] <- TRUE
  saveRDS(object=prgrss, file=fl)
}

#' @name rstPrgrss
#' @title Reset progress
#' @description Reset progress to an earlier completed stage.
#' @details For example, resettting the progress to 'download'
#' mark stages 'download', 'cluster' and 'align' as un-run.
#' @param wd Working directory
#' @param stg Stage to which the pipeline will be reset
rstPrgrss <- function(wd, stg) {
  fl <- file.path(wd, 'cache', 'progress.RData')
  prgrss <- readRDS(file=fl)
  i <- which(names(prgrss) == stg)
  prgrss[i:length(prgrss)] <- FALSE
  saveRDS(object=prgrss, file=fl)
}

#' @name rdPrgrss
#' @title Read the progress from cache
#' @description Return the last completed stage using the cache.
#' @param wd Working directory
rdPrgrss <- function(wd) {
  fl <- file.path(wd, 'cache', 'progress.RData')
  prgrss <- readRDS(file=fl)
  names(prgrss)[sum(prgrss) + 1]
}

#' @name setUpCch
#' @title Set-up a cache
#' @description Creates a cache of parameters in the wd.
#' @param ps Paramters list generated by \code{setUpPrmtrs}.
#' @param ovrwrt Overwrite existing cache? Default FALSE.
#' @details Warning: overwriting with this function will
#' delete the existing cache.
setUpCch <- function(ps, ovrwrt=FALSE) {
  d <- file.path(ps[['wd']], 'cache')
  if(file.exists(d)) {
    if(!ovrwrt) {
      stop('Cache already exists, ovrwrt=FALSE.')
    } else {
      rmCch(ps[['wd']])
    }
  }
  dir.create(d)
  dir.create(file.path(d, 'ncbi'))
  dir.create(file.path(d, 'ncbi', 'search'))
  dir.create(file.path(d, 'ncbi', 'search', 'taxonomy'))
  dir.create(file.path(d, 'ncbi', 'search', 'nucleotide'))
  dir.create(file.path(d, 'ncbi', 'search', 'nuccore'))
  dir.create(file.path(d, 'ncbi', 'fetch'))
  dir.create(file.path(d, 'ncbi', 'fetch', 'taxonomy'))
  dir.create(file.path(d, 'ncbi', 'fetch', 'nucleotide'))
  dir.create(file.path(d, 'ncbi', 'fetch', 'nuccore'))
  dir.create(file.path(d, 'ncbi', 'summary'))
  dir.create(file.path(d, 'ncbi', 'summary', 'taxonomy'))
  dir.create(file.path(d, 'ncbi', 'summary', 'nucleotide'))
  dir.create(file.path(d, 'ncbi', 'summary', 'nuccore'))
  dir.create(file.path(d, 'clstrs'))
  dir.create(file.path(d, 'sqs'))
  dir.create(file.path(d, 'blast'))
  saveRDS(object=ps,
          file=file.path(d, 'prmtrs.RData'))
}

#' @name ldPrmtrs
#' @title Load paramters from cache
#' @description Parameters are held in cache, use
#' this function to load parameters set for a wd.
#' @param wd Working directory
ldPrmtrs <- function(wd) {
  fl <- file.path(wd, 'cache', 'prmtrs.RData')
  if(file.exists(fl)) {
    ps <- readRDS(file=fl)
  } else {
    stop('Cache does not exist.')
  }
  ps
}

#' @name chkObj
#' @title Check if an object exists
#' @description Check if an object exists in the cache.
#' @param wd Working directory
#' @param nm Object name
chkObj <- function(wd, nm) {
  fl <- file.path(wd, 'cache', paste0(nm, '.RData'))
  file.exists(fl)
}

#' @name ldObj
#' @title Load a named object from the cache
#' @description Loads an object from the cache
#' as stored by \code{svObj}
#' @param wd Working directory
#' @param nm Object name
ldObj <- function(wd, nm) {
  fl <- file.path(wd, 'cache', paste0(nm, '.RData'))
  if(!file.exists(fl)) {
    stop(paste0('No [', nm, '] in [',
                wd, '] cache.'))
  }
  readRDS(file=fl)
}

#' @name svObj
#' @title Aave a named object in the cache
#' @description Save an object in the cache
#' that can be loaded by \code{ldObj}
#' @param wd Working directory
#' @param obj Object
#' @param nm Object name
svObj <- function(wd, obj, nm) {
  d <- file.path(wd, 'cache')
  if(!file.exists(d)) {
    dir.create(d)
  }
  fl <- file.path(wd, 'cache', paste0(nm, '.RData'))
  saveRDS(object=obj, file=fl)
}

#' @name rmCch
#' @title Delete a cache
#' @description Deletes a cache from a wd.
#' @param wd Working directory
rmCch <- function(wd) {
  d <- file.path(wd, 'cache')
  if(file.exists(d)) {
    unlink(d, recursive=TRUE)
  }
}

#' @name svSqs
#' @title Save sequences to cache
#' @description Saves sequences downloaded
#' @param wd Working directory
#' @param txid Taxonomic ID, numeric
#' @param sqs Sequences
#' @details Used within the \code{dwnld} function. Saves
#' sequence data by txid in cache.
svSqs <- function(wd, txid, sqs) {
  # TODO: avoid overwriting
  d <- file.path(wd, 'cache')
  if(!file.exists(d)) {
    stop('Cache does not exist.')
  }
  d <- file.path(d, 'sqs')
  if(!file.exists(d)) {
    dir.create(d)
  }
  fl <- file.path(d, paste0(txid, '.RData'))
  saveRDS(object=sqs, file=fl)
}

#' @name ldSqs
#' @title Load sequences from cache
#' @description Load sequences downloaded by
#' \code{dwnld} function.
#' @param wd Working directory
#' @param txid Taxonomic ID, numeric
ldSqs <- function(wd, txid) {
  d <- file.path(wd, 'cache')
  if(!file.exists(d)) {
    stop('Cache does not exist.')
  }
  d <- file.path(d, 'sqs')
  if(!file.exists(d)) {
    stop('`sqs` not in cache. Have you run the download stage?')
  }
  fl <- file.path(d, paste0(txid, '.RData'))
  if(!file.exists(fl)) {
    stop(paste0('[', txid, '] not in `sqs` of cache.'))
  }
  readRDS(file=fl)
}

#' @name svClstrs
#' @title Save clusters to cache
#' @description Saves clusters generated by clstrAll to cache.
#' @param wd Working directory
#' @param txid Taxonomic ID, numeric
#' @param clstrs cluster list
svClstrs <- function(wd, txid, clstrs) {
  d <- file.path(wd, 'cache')
  if(!file.exists(d)) {
    stop('Cache does not exist.')
  }
  d <- file.path(d, 'clstrs')
  if(!file.exists(d)) {
    dir.create(d)
  }
  fl <- file.path(d, paste0(txid, '.RData'))
  saveRDS(object=clstrs, file=fl)
}

#' @name ldNcbiCch
#' @title Retrieve cached NCBI query
#' @description Run this function to load cached NCBI queries.
#' @param fnm NCBI Entrez function name
#' @param args Args used for function
#' @param wd Working directory
ldNcbiCch <- function(fnm, args, wd) {
  flpth <- file.path(wd, 'cache', 'ncbi',
                     fnm, args[['db']])
  fldctnry_pth <- file.path(flpth, 'fldctnry.RData')
  if(file.exists(fldctnry_pth)) {
    fldctnry <- readRDS(fldctnry_pth)
  } else {
    return(NULL)
  }
  if(fnm == 'search') {
    id <- paste0('TERM_', args[['term']],
                 '_RETSTART_', args[['retstart']],
                 '_RETMAX_', args[['retmax']])
    pull <- sapply(fldctnry, function(x) id == x)
  } else {
    id <- args[['id']]
    pull <- sapply(fldctnry, function(x) all(id %in% x) &
                     all(x %in% id))
  }
  if(sum(pull) == 0) {
    return(NULL)
  }
  flnm <- paste0(which(pull), '.RData')
  flpth <- file.path(flpth, flnm)
  readRDS(file=flpth)
}

#' @name svNcbiCch
#' @title Save NCBI query result to cache
#' @description Run whenever NCBI queries are made to save
#' results in cache in case the pipeline is run again.
#' @param fnm NCBI Entrez function name
#' @param args Args used for function
#' @param wd Working directory
#' @param obj NCBI query result
svNcbiCch <- function(fnm, args, wd, obj) {
  flpth <- file.path(wd, 'cache', 'ncbi',
                     fnm, args[['db']])
  fldctnry_pth <- file.path(flpth, 'fldctnry.RData')
  if(file.exists(fldctnry_pth)) {
    fldctnry <- readRDS(fldctnry_pth)
  } else {
    fldctnry <- list()
  }
  if(fnm == 'search') {
    # construct unique identifier from args
    id <- paste0('TERM_', args[['term']],
                 '_RETSTART_', args[['retstart']],
                 '_RETMAX_', args[['retmax']])
  } else {
    # ids are sufficient
    id <- args[['id']]
  }
  fldctnry[[length(fldctnry) + 1]] <- id
  flnm <- paste0(length(fldctnry), '.RData')
  flpth <- file.path(flpth, flnm)
  saveRDS(object=obj, file=flpth)
  saveRDS(object=fldctnry, file=fldctnry_pth)
}

#' @name ldBlstCch
#' @title Load BLAST results from cache
#' @description Run to load cached BLAST results.
#' @param sids Sequence IDs
#' @param wd Working dir
ldBlstCch <- function(sids, wd) {
  # fldctnry contains all the IDs of the sequences used in a BLAST
  fldctnry_pth <- file.path(wd, 'cache', 'blast',
                            'fldctnry.RData')
  if(file.exists(fldctnry_pth)) {
    fldctnry <- readRDS(fldctnry_pth)
  } else {
    return(NULL)
  }
  pull <- sapply(fldctnry, function(x) all(sids %in% x))
  if(sum(pull) == 0) {
    return(NULL)
  }
  if(sum(pull) == 0) {
    flnm <- paste0(which(pull), '.RData')
    flpth <- file.path(wd, 'cache', 'blast', flnm)
    return(readRDS(file=flpth))
  }
  pssbls <- which(pull)
  lngs <- sapply(fldctnry[pssbls], length)
  flnm <- paste0(pssbls[which.min(lngs)], '.RData')
  flpth <- file.path(wd, 'cache', 'blast', flnm)
  blst_rs <- readRDS(file=flpth)
  pull <- blst_rs[['query.id']] %in% sids &
    blst_rs[['subject.id']] %in% sids
  blst_rs[pull, ]
}

#' @name svBlstCch
#' @title Save BLAST results to cache
#' @description Run whenever local BLAST runs are made to save
#' results in cache in case the pipeline is run again.
#' @param sids Sequence IDs
#' @param wd Working dir
#' @param obj BLAST result
svBlstCch <- function(sids, wd, obj) {
  # fldctnry contains all the IDs of the sequences used in a BLAST
  fldctnry_pth <- file.path(wd, 'cache', 'blast', 'fldctnry.RData')
  if(file.exists(fldctnry_pth)) {
    fldctnry <- readRDS(fldctnry_pth)
  } else {
    fldctnry <- list()
  }
  fldctnry[[length(fldctnry) + 1]] <- sids
  flnm <- paste0(length(fldctnry), '.RData')
  flpth <- file.path(wd, 'cache', 'blast', flnm)
  saveRDS(object=obj, file=flpth)
  saveRDS(object=fldctnry, file=fldctnry_pth)
}