# Tools for running tests
#' @title Return test data directory
#' @description Returns the file path to the test data directory.
#' @param subdir Subdirectory within the datadir
#' @return filepath, character
#' @noRd
datadir_get <- function(subdir = NULL) {
  wd <- getwd()
  if (grepl('testthat', wd)) {
    datadir <- 'data'
  } else {
    # for running test at package level
    datadir <- file.path('tests', 'testthat', 'data')
  }
  file.path(datadir, subdir)
}

#' @title Remove all test files and folders
#' @description Any folders and files generated by tests will be deleted.
#' @return NULL
#' @noRd
cleanup <- function() {
  # remove any test generated datasets
  if (file.exists('cache')) {
    unlink('cache', recursive = TRUE)
  }
  if (file.exists('log.txt')) {
    file.remove('log.txt')
  }
}

#' @title Run cmdln for BLAST checking
#' @description Use command arg to control returned output and testing function
#' responses.
#' @return list
#' @noRd
cmdln_blastcheck <- function(cmd, args, lgfl = NULL) {
  if (grepl('makeblastdb', cmd)) {
    out <- "makeblastdb: 2.7.1+\nPackage: blast 2.7.1, build Oct 18 2017 19:57"
  }
  if (grepl('blastn', cmd)) {
    out <- "blastn: 2.7.1+\nPackage: blast 2.7.1, build Oct 18 2017 19:57"
  }
  if (grepl('wrngvrsn', cmd)) {
    out <- "blastn: 1.6.1+\nPackage: blast 1.6.1, build Oct 18 2017 19:57"
  }
  list(status = 0, stdout = charToRaw(out), stderr = charToRaw(''))
}

# efetch_mock <- function(db, rettype, id) {
#   fasta_rand <- function() {
#     seq <- sample(c('A', 'T', 'C', 'G'), size = 1000,
#                   replace = TRUE)
#     seq <- paste(seq, collapse = '')
#     paste0('> rand0m.name.--jg82-5969\n', seq, '\n')
#   }
#   seqs <- ''
#   for (i in 1:length(id)) {
#     seqs <- paste0(seqs, fasta_rand())
#   }
#   seqs
# }

# esummary_mock <- function(db, id) {
#   summary_rand <- function() {
#     list(uid = NA, txid = NA, caption = NA,
#          accessionversion = NA,
#          slen = NA, createdate = NA, title = NA)
#   }
#   if (n == 1) {
#     return(summary_rand())
#   }
#   summ <- vector('list', length = n)
#   for (i in 1:length(id)) {
#     summ[[i]] <- summary_rand()
#   }
#   summ
# }

# sids_get_mock <- function(...) {
#   if (n == 0) {
#     ids <- NULL
#   } else {
#     ids <- as.character(1:n)
#   }
#   ids
# }