# Tools for running tests
#' @title Return test data directory
#' @description Returns the file path to the test data directory.
#' @param subdir Subdirectory within the datadir
#' @return filepath, character
#' @noRd
datadir_get <- function(subdir = NULL) {
  wd <- getwd()
  if (grepl('testthat', wd)) {
    datadir <- 'data'
  } else {
    # for running test at package level
    datadir <- file.path('tests', 'testthat', 'data')
  }
  file.path(datadir, subdir)
}

#' @title Remove all test files and folders
#' @description Any folders and files generated by tests will be deleted.
#' @return NULL
#' @noRd
cleanup <- function() {
  # remove any test generated datasets
  if (file.exists('cache')) {
    unlink('cache', recursive = TRUE)
  }
}